---
hivemq:
  host: "broker.hivemq.com"
  port: "1883"
  username: ""
  password: ""
  # TODO: maybe just subscribe on each "from" mapped_topic
  subscribed_topics:
    - "debuglevel/OpenMQTTGateway/gateways/byMac/#"
  mapped_topics:
    - from: "debuglevel/OpenMQTTGateway/gateways/byMac/30C6F7001130"
      to:
        - "debuglevel/OpenMQTTGateway/gateways/byName/ESP32-01"
        - "debuglevel/devnull/"
  ssl: false


# FLESPI:
#   host: "mqtt.flespi.io"
#   port: "8883"
#   username: ""
#   password: ""
#   topics:
#     - "BRIDGE/#"
#   ssl: yes
# RU_FLESPI:
#   host: "ru-mqtt.flespi.io"
#   port: "8883"
#   username: ""
#   password: ""
#   topics:
#     - "REFRIGERATOR/#"
#     - "LIGHT/#"
#   ssl: yes
# LOCAL:
#   host: "127.0.0.1"
#   port: "1883"
#   username: ""
#   password: ""
#   topics:
#     - "zigbee2mqtt/#"
#     - "homeassistant/#"
#   ssl: no
